name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: With pytest for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install poetry
        run: pipx install poetry

      - name: ğŸ› ï¸ Set up Python
        uses: actions/setup-python@v4.7.0
        id: python
        with:
          python-version: "${{ matrix.python_version }}"
          cache: "poetry"

      - name: ğŸ“¦ Install requirements
        run: task setup

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: task tests

      - name: ğŸ“¤ Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.10' }}
        run: |
          task coverage
          curl -sfSL https://codecov.io/bash | bash -

  legacy:
    name: With pytest with Home Assistant 2022.11.0
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install poetry
        run: pipx install poetry

      - name: ğŸ› ï¸ Set up Python 3.9
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.9"
          cache: "poetry"

      - name: ğŸ“¦ Install dependencies
        run: task setup

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: task tests
